name: Handle Release

on:
  release:
    types: [created]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build services
        run: pnpm run build

      - name: Test services
        run: pnpm run test

      - name: "Setup up JDK 21"
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: "maven"

      - name: "Build with Maven"
        run: mvn package -f ./plugin/pom.xml

      - name: "Upload Release Assets"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./plugin/target/natural-commands.jar
          asset_name: natural-commands.jar
          asset_content_type: application/java-archive