name: Handle Release

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Setup up JDK 21"
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: "maven"

      - name: "Build with Maven"
        run: mvn package -f ./plugin/pom.xml

      - name: "Upload release asset"
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./plugin/target/*.jar